### ISSUE TITLE
ImportError: cannot import name get_redis_connection

### ISSUE THREAD

**Issue by EswarSakamuri** [rapidpro/ureport#98]
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/administrator/workspace/ureportenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/administrator/workspace/ureportenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/administrator/workspace/ureportenv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/administrator/workspace/ureportenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/administrator/workspace/ureportenv/local/lib/python2.7/site-packages/django/apps/config.py", line 119, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/administrator/workspace/ureport/ureport/admins/__init__.py", line 1, in <module>
    from dash.orgs.models import Org
  File "/home/administrator/workspace/ureportenv/src/dash/dash/orgs/models.py", line 18, in <module>
    from dash.api import API
  File "/home/administrator/workspace/ureportenv/src/dash/dash/api/__init__.py", line 6, in <module>
    from redis_cache import get_redis_connection
ImportError: cannot import name get_redis_connection

**Comment by xkmato** [comment]
My guess is that you're using the wrong or outdated python redis lib. Make sure you env's pip freeze output is the same as the contents of pip-freeze.txt

**Comment by EswarSakamuri** [comment]
With pip-freeze.txt its working fine I got previous error when installed with pip-requires.txt

one more thing when creating a symbolic link using 
ln -s ureport/settings.py.postgres ureport/settings.py

python manage.py syncdb giving me this error 
ImportError: No module named settings(Did I make any mistake in running the sync command?)

at present I created a fresh copy of settings.py from settings_common.py

**Comment by xkmato** [comment]
Just make a copy instead of link do `cp ureport/settings.py.postgres ureport/settings.py` instead

**Comment by norkans7** [comment]
Symlink is the right thing instead of copy, even if either will work

**Comment by norkans7** [comment]
about the dependencies, yes pip-requires  might install newer version which might break, pip freeze has pinned versions

**Comment by xkmato** [comment]
@norkans7 sym link doesn't work very consistently especially on Mac. It has never worked on my dev env, although it works fine on server

**Comment by EswarSakamuri** [comment]
Yes for without sym link its working fine for me

**Comment by nicpottier** [comment]
Symlinks are definitely consistent on Mac's as they are POSIX. How exactly are you symlinking?

**Comment by badbye** [comment]
Get the same error when running the single command in python:
```
>>> from redis_cache import get_redis_connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name get_redis_connection
```

**Comment by EswarSakamuri** [comment]
Do pip install with "pip-freeze.txt"

If your setting up in Linux skip this step
ln -s ureport/settings.py.postgres ureport/settings.py
